In [ ]:
import numpy as np
import pandas as pd

# Problem 1

In [ ]:
arr1 = np.random.randint(1, 51, size=(5, 4))
print("Array:\n", arr1)

Array:
 [[44 15  9 20]
 [29  9 12 16]
 [41 11 47 49]
 [36 45 36 15]
 [24 19  7 29]]


In [ ]:
anti_diag = [int(arr1[i, -i - 1]) for i in range(min(arr1.shape))]
print("Anti-diagonal:", anti_diag)

Anti-diagonal: [20, 12, 11, 36]


In [ ]:
row_max = np.max(arr1, axis=1)
print("Row-wise Max:", row_max)

Row-wise Max: [44 29 49 45 29]


In [ ]:
mean_val = np.mean(arr1)
less_eq_mean = arr1[arr1 <= mean_val]
print("Elements <= mean (", mean_val, "):\n", less_eq_mean)

Elements <= mean ( 25.65 ):
 [15  9 20  9 12 16 11 15 24 19  7]


In [ ]:
def numpy_boundary_traversal(matrix):
    rows, cols = matrix.shape
    boundary = []
    for j in range(cols):
        boundary.append(int(matrix[0, j]))
    for i in range(1, rows):
        boundary.append(int(matrix[i, cols - 1]))
    if rows > 1:
        for j in range(cols - 2, -1, -1):
            boundary.append(int(matrix[rows - 1, j]))
    if cols > 1:
        for i in range(rows - 2, 0, -1):
            boundary.append(int(matrix[i, 0]))

    return boundary


print("Boundary Traversal:", numpy_boundary_traversal(arr1))

Boundary Traversal: [44, 15, 9, 20, 16, 49, 15, 29, 7, 19, 24, 36, 41, 29]


# Problem 2

In [ ]:
arr2 = np.random.uniform(0, 10, 20)
arr2 = np.round(arr2, 2)
print("Array:", arr2)

Array: [3.78 5.23 7.57 0.07 6.05 4.44 1.13 9.51 0.59 5.64 7.97 9.58 1.85 2.44
 2.3  9.43 7.29 0.29 8.61 1.76]


In [ ]:
print("Min:", np.min(arr2))
print("Max:", np.max(arr2))
print("Median:", np.median(arr2))

Min: 0.07
Max: 9.58
Median: 4.835000000000001


In [ ]:
arr2_transformed = np.where(arr2 < 5, arr2**2, arr2)
print("Transformed:", arr2_transformed)

Transformed: [1.42884e+01 5.23000e+00 7.57000e+00 4.90000e-03 6.05000e+00 1.97136e+01
 1.27690e+00 9.51000e+00 3.48100e-01 5.64000e+00 7.97000e+00 9.58000e+00
 3.42250e+00 5.95360e+00 5.29000e+00 9.43000e+00 7.29000e+00 8.41000e-02
 8.61000e+00 3.09760e+00]


In [ ]:
def numpy_alternate_sort(array):
    sorted_arr = np.sort(array)
    result = []
    i, j = 0, len(sorted_arr) - 1
    while i <= j:
        result.append(sorted_arr[i])
        if i != j:
            result.append(sorted_arr[j])
        i += 1
        j -= 1
    return np.array(result)

print("Alternate Sort:", numpy_alternate_sort(arr2))


Alternate Sort: [0.07 9.58 0.29 9.51 0.59 9.43 1.13 8.61 1.76 7.97 1.85 7.57 2.3  7.29
 2.44 6.05 3.78 5.64 4.44 5.23]


#Problem 3

In [ ]:
names = [f"Student{i}" for i in range(1, 11)]
subjects = ["Math", "Science", "History", "English", "Art"]
data = {
    "Name": names,
    "Subject": np.random.choice(subjects, size=10),
    "Score": np.random.randint(50, 101, size=10),
    "Grade": [""] * 10
}
df = pd.DataFrame(data)
df

Name  Subject  Score Grade
0   Student1  History     50      
1   Student2  History     69      
2   Student3  Science     69      
3   Student4  English     62      
4   Student5  History     62      
5   Student6  History     74      
6   Student7  Science     84      
7   Student8     Math     61      
8   Student9  Science     63      
9  Student10      Art     58

In [ ]:
conditions = [
    (df['Score'] >= 90),
    (df['Score'] >= 80),
    (df['Score'] >= 70),
    (df['Score'] >= 60),
    (df['Score'] < 60)
]
grades = ['A', 'B', 'C', 'D', 'F']
df['Grade'] = np.select(conditions, grades,default='F')
df

Name  Subject  Score Grade
0   Student1  History     50     F
1   Student2  History     69     D
2   Student3  Science     69     D
3   Student4  English     62     D
4   Student5  History     62     D
5   Student6  History     74     C
6   Student7  Science     84     B
7   Student8     Math     61     D
8   Student9  Science     63     D
9  Student10      Art     58     F

In [ ]:
df_sorted = df.sort_values(by='Score', ascending=False)
print(df_sorted)

        Name  Subject  Score Grade
6   Student7  Science     84     B
5   Student6  History     74     C
2   Student3  Science     69     D
1   Student2  History     69     D
8   Student9  Science     63     D
4   Student5  History     62     D
3   Student4  English     62     D
7   Student8     Math     61     D
9  Student10      Art     58     F
0   Student1  History     50     F


In [ ]:
print("Average Score per Subject:")
print(df.groupby('Subject')['Score'].mean())

Average Score per Subject:
Subject
Art        58.00
English    62.00
History    63.75
Math       61.00
Science    72.00
Name: Score, dtype: float64


In [ ]:
def pandas_filter_pass(dataframe):
    return dataframe[dataframe['Grade'].isin(['A', 'B'])]

print("Passed Students:")
print(pandas_filter_pass(df))

Passed Students:
       Name  Subject  Score Grade
6  Student7  Science     84     B


#Problem 4

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [ ]:
positive_reviews = [
    "I loved this movie, it was fantastic!", "Amazing acting and great story.",
    "What a masterpiece!", "Brilliant film with an emotional plot.",
    "Great direction and superb cast!", "Absolutely wonderful movie.",
    "Beautifully shot and well-acted.", "A compelling and uplifting story.",
    "Top-notch performances by all actors.", "It touched my heart.",
    "A cinematic triumph!", "Spectacular visuals and touching script.",
    "Thoroughly entertaining.", "Incredible storytelling.",
    "Heartwarming and inspiring.", "Stellar screenplay and execution.",
    "A must-watch for everyone.", "The best film I’ve seen this year.",
    "Emotionally resonant.", "I can't stop thinking about it.",
    "Flawless movie experience.", "Powerful and moving.",
    "Absolutely breathtaking.", "A visual treat.",
    "One of the finest films.", "Brilliantly executed.",
    "An emotional rollercoaster.", "Quality filmmaking.",
    "Beautiful and moving.", "Highly recommended.",
    "Fantastic storytelling.", "Wonderful pacing.",
    "A true classic.", "Mesmerizing.",
    "Left me speechless.", "Impeccable direction.",
    "Perfect in every way.", "Made me cry and smile.",
    "Loved it from start to end.", "Magical experience.",
    "Masterfully made.", "Heartfelt and genuine.",
    "Joyful and inspiring.", "An artistic gem.",
    "A beautiful film.", "Exceeded expectations.",
    "Hits all the right notes.", "Gripping and emotional.",
    "Rich and fulfilling film.", "Will watch again."
]

negative_reviews = [
    "I hated this movie, it was awful.", "Terrible acting and weak story.",
    "A complete waste of time.", "Poorly executed and boring.",
    "Bad direction and worse acting.", "A disappointing film.",
    "Clumsy editing and flat characters.", "Dull and lifeless script.",
    "I fell asleep halfway through.", "Unbelievably bad.",
    "Just horrible.", "Amateurish in every way.",
    "Predictable and cliché plot.", "Embarrassing movie.",
    "Felt like a school project.", "Painful to watch.",
    "Terribly written and acted.", "Regret watching this.",
    "Everything was poor.", "Simply not worth it.",
    "Lazy filmmaking.", "No redeeming qualities.",
    "An insult to cinema.", "A total mess.",
    "Dragged with no point.", "Made no sense.",
    "Emotionless and flat.", "Weak storytelling.",
    "Didn’t engage me.", "Disjointed and frustrating.",
    "Too many flaws.", "Confusing and boring.",
    "Miscast and mishandled.", "Lacked effort.",
    "Underwhelming.", "Not entertaining.",
    "Plot went nowhere.", "Wasted potential.",
    "Cringe-worthy scenes.", "Regret watching.",
    "Forgettable movie.", "No character depth.",
    "Unwatchable.", "Boring beginning to end.",
    "Fast-forwarded most of it.", "Nothing worked.",
    "Cheap and unconvincing.", "A total disaster.",
    "Left disappointed.", "Couldn't finish it."
]

In [ ]:
df = pd.DataFrame({
    'Review': positive_reviews + negative_reviews,
    'Sentiment': ['positive'] * 50 + ['negative'] * 50
})


In [ ]:
vectorizer = CountVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(df['Review'])
y = df['Sentiment']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
model = MultinomialNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", accuracy)

Test Accuracy: 0.7


In [ ]:
def predict_review_sentiment(model, vectorizer, review):
    vec = vectorizer.transform([review])
    return model.predict(vec)[0]

print(predict_review_sentiment(model, vectorizer, "This movie was absolutely amazing!"))
print(predict_review_sentiment(model, vectorizer, "Boring and a complete waste of time."))

positive
negative


#Problem 5

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [ ]:
good_feedbacks = [
    "Excellent product quality!", "Very satisfied with the purchase.",
    "Highly recommend this item.", "Works perfectly, no complaints.",
    "Amazing value for the price.", "Superb build and performance.",
    "Will buy again!", "Exceeded my expectations.",
    "The product arrived on time and was well packaged.",
    "Impressive features and easy to use.",
    "Absolutely love it!", "Five stars from me.",
    "Sturdy and reliable.", "Top-notch product.",
    "Exactly as described.", "Really happy with it.",
    "Customer service was also great.", "Solid choice for the price.",
    "Smooth experience overall.", "Worth every penny.",
    "Fantastic quality.", "Happy with the results.",
    "Simple and efficient.", "Pleasantly surprised!",
    "Item matched the description.", "Fast delivery and great quality.",
    "Perfect for my needs.", "Durable and efficient.",
    "Highly functional.", "Elegant and modern design.",
    "Everything works as expected.", "Reliable and trustworthy.",
    "Would definitely recommend.", "User-friendly and effective.",
    "Product does what it promises.", "Easy setup and great output.",
    "Practical and useful.", "Impressive performance.",
    "Compact and powerful.", "I would rate this 10/10.",
    "Affordable and effective.", "Met all my expectations.",
    "No regrets buying this.", "Product is as advertised.",
    "Overall a great buy.", "Very pleased with this item.",
    "Perfect in every way.", "Totally satisfied.",
    "Great user experience.", "Thumbs up!"
]

bad_feedbacks = [
    "Terrible quality.", "Not worth the money.",
    "I regret buying this.", "Very disappointing product.",
    "Broke within days.", "Stopped working after a week.",
    "Completely useless.", "The worst I've ever bought.",
    "Would not recommend.", "Do not waste your money.",
    "Misleading description.", "Does not work as advertised.",
    "Cheap materials used.", "Totally dissatisfied.",
    "Frustrating experience.", "Not user-friendly at all.",
    "Feels very flimsy.", "Horrible customer service.",
    "Overpriced and underperforming.", "Doesn’t function properly.",
    "The product is defective.", "Shipping was delayed too.",
    "Item was missing parts.", "Very poor quality control.",
    "Looks nice but performs badly.", "Unreliable and inconsistent.",
    "It’s already broken.", "Not durable at all.",
    "Instructions were confusing.", "Faulty and unsafe.",
    "Terrible value for money.", "Returned immediately.",
    "Not what I expected.", "Far from satisfactory.",
    "Too difficult to use.", "No support available.",
    "Disappointed with the results.", "Waste of money.",
    "Low-quality build.", "I want a refund.",
    "Design is flawed.", "Stopped functioning quickly.",
    "Never buying this brand again.", "It feels really cheap.",
    "Unimpressive and clunky.", "Doesn’t meet expectations.",
    "Not suitable for long-term use.", "Incredibly slow.",
    "The performance is poor.", "Won't recommend to anyone."
]

In [ ]:
df = pd.DataFrame({
    'Feedback': good_feedbacks + bad_feedbacks,
    'Label': ['good'] * 50 + ['bad'] * 50
})


In [ ]:
vectorizer = TfidfVectorizer(stop_words='english', max_features=300, lowercase=True)
X = vectorizer.fit_transform(df['Feedback'])  # X is a sparse matrix
y = df['Label']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)
print("Classification Report on Test Set:")
print(classification_report(y_test, y_pred))

Classification Report on Test Set:
              precision    recall  f1-score   support

         bad       0.43      0.55      0.48        11
        good       0.55      0.43      0.48        14

    accuracy                           0.48        25
   macro avg       0.49      0.49      0.48        25
weighted avg       0.49      0.48      0.48        25



In [ ]:
def text_preprocess_vectorize(texts, vectorizer):
    return vectorizer.transform(texts)

sample_texts = ["This product is amazing!", "Worst thing I ever bought."]
sample_vectors = text_preprocess_vectorize(sample_texts, vectorizer)
predictions = model.predict(sample_vectors)
print("Predictions for sample texts:", list(zip(sample_texts, predictions)))

Predictions for sample texts: [('This product is amazing!', 'good'), ('Worst thing I ever bought.', 'bad')]
